### ISSUE TITLE
 net.sf.jasperreports.engine.JRException: Class not found when loading object from file: reports\relatorio-pai.jasper.

### ISSUE THREAD

**Issue by miguelf03kai** [sibelly/jasper-subrelatorios#1]
Olá, eu estava estudando seu incrível algoritmo, mas quando executo o App.java eu o obtenho  **ERRO AO GERAR PDF com.jasper.exemploverificavel.entidades.Cliente@1060b431**, dai fui fazer o debug descobri que  a exceção gerada é  **net.sf.jasperreports.engine.JRException: Class not found when loading object from file: reports\relatorio-pai.jasper**. Eu configurei o path dos arquivos de acordo com meu ambiente, mas não achei onde esta o erro é como se tivesse alguma classe no arquivo que não é encontrada, poderia me ajudar?

meu ambiente é windows setei o caminho assim.

_**String caminhoArquivo = "reports/relatorio-pai.jasper";
String subReportDir = "reports/";**_

Desde de já agradeço.

**Comment by sibelly** [comment]
Opaa, faz tempo esse projetinho ein.

Bem, no código é o caminho absoluto

```
// Meu diretorio 
String caminhoArquivo = "/home/boogiepop/Documents/relatorio-pai.jasper";
String subReportDir = "/home/boogiepop/Documents/";
```

Desde o home etc, se não me engano eu usava windows tbm e a IDE Netbeans.
Tenta colocar todo o caminho de onde está seu arquivo.

Inclusive colocando a barra no começo tbm:

de:
```String caminhoArquivo = "reports/relatorio-pai.jasper";```

para:
```String caminhoArquivo = "/reports/relatorio-pai.jasper";```

https://learn.microsoft.com/pt-br/dotnet/standard/io/file-path-formats

**Comment by miguelf03kai** [comment]
Olá @sibelly ! Eu ajustei o caminho mas obtenho o mesmo erro, testei na VM linux que tenho usando o caminho absoluto, mesmo erro também, durante o debug vi que o aquivo é encontrado, o que parece é que alguma classe presente no arquivo não é encontrada, será se é algum parametro? Está difícil encontrar o erro pois durante minha inspeção no **jrxml** não encontrei nada de errado nas declarações de paramentros e nem classes.

**Comment by sibelly** [comment]
Pode ser algo de versão então, da lib (jasperreports, nesse projeto é a 6.4.1).

Achei isso [aqui](https://stackoverflow.com/questions/6649886/jasperreports-filling-a-report-throws-an-exception-class-not-found-when-loadin) e [isso](https://www.guj.com.br/t/class-not-found-when-loading-object-from-file/102854/15).

Parece muito coisa de lib e versões incompatíveis etc, tenta ir nessa linha.

**Comment by miguelf03kai** [comment]
Obrigado @sibelly pela ajuda, atualizei o jasperreports para a varsão 6.17.0 e removi a field **class** que estava sem utilidade no jrxml do sub-relatorio e funcionou normalmente.

Novamente, muito obrigado! Graças ao seu código consegui implementar em um sistema emissor de recibos com 2 vias. :thumbsup:
